const coinName = {
  bithumb: {
    BTC: "비트코인",
    ETH: "이더리움",
    DASH: "대시",
    LTC: "라이트코인",
    ETC: "이더리움 클래식",
    XRP: "리플",
    BCH: "비트코인 캐시",
    XMR: "모네로",
    ZEC: "제트캐시",
    QTUM: "퀀텀",
    BTG: "비트코인 골드",
    EOS: "이오스",
    ICX: "아이콘",
    VET: "비체인",
    TRX: "트론",
    ELF: "엘프",
    MITH: "미스릴",
    MCO: "크립토닷컴",
    OMG: "오미세고",
    KNC: "카이버 네트워크",
    GNT: "골렘",
    ZIL: "질리카",
    ETHOS: "에토스",
    PAY: "텐엑스",
    WAX: "왁스",
    POWR: "파워렛져",
    LRC: "루프링",
    GTO: "기프토",
    STEEM: "스팀",
    STRAT: "스트라티스",
    ZRX: "제로엑스",
    REP: "어거",
    AE: "애터니티",
    XEM: "넴",
    SNT: "스테이터스네트워크토큰",
    ADA: "에이다",
    PPT: "파퓰러스",
    CTXC: "코르텍스",
    CMT: "사이버마일즈",
    THETA: "쎄타토큰",
    WTC: "울턴체인",
    ITC: "아이오티체인",
    TRUE: "트루체인",
    ABT: "아크블록",
    RNT: "원루트 네트워크",
    PLY: "플레이코인",
    WAVES: "웨이브",
    LINK: "체인링크",
    ENJ: "엔진코인",
    PST: "프리마스",
    SALT: "솔트",
    RDN: "레이든네트워크토큰",
    LOOM: "룸네트워크",
    PIVX: "피벡스",
    INS: "아이앤에스",
    BCD: "비트코인 다이아몬드",
    BZNT: "베잔트",
    XLM: "스텔라루멘",
    OCN: "오디세이",
    BSV: "비트코인에스브이",
    TMTG: "더마이다스터치골드",
    BAT: "베이직어텐션토큰",
    WET: "위쇼토큰",
    XVG: "버지",
    IOST: "이오스트",
    POLY: "폴리매스",
    HC: "하이퍼캐시",
    ROM: "롬",
    AMO: "아모코인",
    ETZ: "이더제로",
    ARN: "에어론",
    APIS: "아피스",
    MTL: "메탈",
    DACC: "디에이씨씨",
    DAC: "다빈치",
    BHP: "비에이치피",
    BTT: "비트토렌트",
    HDAC: "에이치닥",
    NPXS: "펀디엑스",
    AUTO: "큐브",
    GXC: "지엑스체인",
    ORBS: "오브스",
    VALOR: "밸러토큰",
    CON: "코넌",
    ANKR: "앵커",
    MIX: "믹스마블",
    HYC: "하이콘",
    LBA: "크레드",
    QKC: "쿼크체인",
    LAMB: "람다",
    CRO: "크립토닷컴체인",
    MXC: "머신익스체인지코인"
  }
};

export { coinName };
